---
global:
  enable_devtools: true

window/bar:
  providers: [self]
  width: "{{ self.args.MONITOR_WIDTH }}"
  height: 45
  position_x: "{{ self.args.MONITOR_X }}"
  position_y: "{{ self.args.MONITOR_Y }}"
  show_in_taskbar: false
  resizable: false

  global_styles: |-
    @import "https://www.nerdfonts.com/assets/css/webfont.css";

  styles: |-
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    color: #ffffffe6;
    font-family: ui-monospace, monospace;
    font-size: 13px;
    padding: 4px 24px;
    border-bottom: 1px solid #ffffff08;
    background: linear-gradient(
      rgba(14, 14, 28, 0.95),
      rgba(26, 14, 28, 0.85),
    );

  group/left:
    styles: |-
      display: flex;
      align-items: center;

    template/logo:
      template: |-
        <i class="nf nf-fa-windows"></i>
      styles: |-
        margin-right: 20px;

    template/glazewm:
      providers: [glazewm]
      template: |-
        @for (workspace of glazewm.workspacesOnMonitor) {
          <button class="workspace">{{ workspace.name }}</button>
        }
      styles: |-
        display: flex;
        align-items: center;

        .workspace {
          background: rgba(255, 255, 255, 0.05);
          margin-right: 4px;
          width: 30px;
          height: 30px;
          color: #ffffffe6;
          border: none;
          border-radius: 2px;
        }

  group/center:
    styles: |-
      justify-self: center;

    template/clock:
      providers: [date]
      template: |-
        {{ date.toFormat(date.now, 'EEE	d MMM t') }}

  group/right:
    styles: |-
      justify-self: end;
      display: flex;

      .template {
        margin-left: 20px;
      }

      i {
        color: #7481b2e1;
        margin-right: 7px;
      }

    template/memory:
      providers: [memory]
      template: |-
        <i class="nf nf-fae-chip"></i>
        {{ Math.round(memory.usage) }}%

    template/cpu:
      providers: [cpu]
      template: |
        <i class="nf nf-oct-cpu"></i>
        <!-- Change the text color if the CPU usage is high. -->
        @if (cpu.usage > 85) {
          <span class="high-usage">{{ Math.round(cpu.usage) }}%</span>
        } @else {
          <span>{{ Math.round(cpu.usage) }}%</span>
        }

      styles: |-
        .high-usage {
          color: #900029;
        }

    template/battery:
      providers: [battery]
      styles: |-
        position: relative;

        .charging-icon {
          position: absolute;
          font-size: 11px;
          left: 7px;
          top: 2px;
        }
      template: |
        <!-- Show icon for whether battery is charging. -->
        @if (battery.isCharging) {<i class="nf nf-md-power_plug charging-icon"></i>}

        <!-- Show icon for how much of the battery is charged. -->
        @if (battery.chargePercent > 90) {<i class="nf nf-fa-battery_4"></i>}
        @else if (battery.chargePercent > 70) {<i class="nf nf-fa-battery_3"></i>}
        @else if (battery.chargePercent > 40) {<i class="nf nf-fa-battery_2"></i>}
        @else if (battery.chargePercent > 20) {<i class="nf nf-fa-battery_1"></i>}
        @else {<i class="nf nf-fa-battery_0"></i>}

        {{ Math.round(battery.chargePercent) }}%

    template/weather:
      providers: [weather]
      template: |-
        @switch (weather.status) {
          @case ('clear_day') {<i class="nf nf-weather-day_sunny"></i>}
          @case ('clear_night') {<i class="nf nf-weather-night_clear"></i>}
          @case ('cloudy_day') {<i class="nf nf-weather-day_cloudy"></i>}
          @case ('cloudy_night') {<i class="nf nf-weather-night_alt_cloudy"></i>}
          @case ('light_rain_day') {<i class="nf nf-weather-day_sprinkle"></i>}
          @case ('light_rain_night') {<i class="nf nf-weather-night_alt_sprinkle"></i>}
          @case ('heavy_rain_day') {<i class="nf nf-weather-day_rain"></i>}
          @case ('heavy_rain_night') {<i class="nf nf-weather-night_alt_rain"></i>}
          @case ('snow_day') {<i class="nf nf-weather-day_snow"></i>}
          @case ('snow_night') {<i class="nf nf-weather-night_alt_snow"></i>}
          @case ('thunder_day') {<i class="nf nf-weather-day_lightning"></i>}
          @case ('thunder_night') {<i class="nf nf-weather-night_alt_lightning"></i>}
        }
        {{ weather.celsiusTemp }}°
